apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: roboshop
  region: us-east-1

managedNodeGroups:
  - name: spot
    instanceType: m5.large
    desiredCapacity: 3
    spot: true


## Manifest file to create EKS cluster 
## Workstation is having ekctl client with IAM CLI access role(Login to workstation and do aws configure). it can create the clsuter if we apply the below manifest file. Backend it uses the cloud formation to create the EKS cluster.

## eksctl create cluster --config-file=<manifest_file> 
## eksctl create cluster -f <manifest_file> 
## eksctl delete cluster -f <manifest_file> 


# Steps to create cluster
# Login to the work station and do aws configure
# git clone https://github.com/hari-palepu/22_K8s_ekctl.git
# eksctl create cluster -f eks.yaml


## commands to install helm
# curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
# chmod 700 get_helm.sh
# ./get_helm.sh